config/routes.rb
Rails.application.routes.draw do
    root to: 'agm#index'

    get '/agm', to:'agm#index'
    get '/agm/admin', to: 'agm#show'

    resources :tours do
      resources :reservations
    end

    resources :shuttles do
      resources :bookings do
        collection do
          get '/date/:date', :action => :index, :as => :date
          post 'dates'
        end
      end
    end
  get  '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get  'logout', to: 'sessions#destroy'

match '*path', to: redirect{|params| "/#{I18n.default_locale}/#{params[:path]}"}, via: :all
match '', to: redirect("/#{I18n.default_locale}"), via: :all


end

app/models/booking.rb
class Booking < ActiveRecord::Base
  belongs_to :shuttle

  belongs_to :from, :class_name => "ShuttleCity"
  belongs_to :to, :class_name => "ShuttleCity"

  before_create :compute_amount
  after_create :charge_credit_card
  after_create :decrement_shuttle_legs

  validates :shuttle_id, :presence => true
  validates :to_id, :presence => true
  validates :from_id, :presence => true
  validates :depart_date, :presence => true
  validates :passengers, :presence => true
  validates :email_address, :presence => true
  validates :telephone_number, :presence => true
  validate :address_fields_status

  default_value_for :round_trip, false

  attr_accessor :token

  def shuttle_legs_departing
    legs = self.shuttle.shuttle_legs.where(:from_id => from, :date => self.depart_date)
    current_city = to.position > from.position ? from.lower_item : from.higher_item

    #intersect the set of dates that match for each leg of the journey if there are multiple legs
    while( current_city && current_city != to )
      legs << self.shuttle.shuttle_legs.where(:from_id => current_city, :date => self.depart_date).first
      current_city = to.position > from.position ? current_city.lower_item : current_city.higher_item

    end

    legs
  end

  def shuttle_legs_returning
    legs = self.shuttle.shuttle_legs.where(:from_id => to, :date => self.return_date)
    current_city = to.position > from.position ? to.higher_item : to.lower_item

    #intersect the set of dates that match for each leg of the journey if there are multiple legs
    while( current_city && current_city != from )
      legs << self.shuttle.shuttle_legs.where(:from_id => current_city, :date => self.return_date).first
      current_city = to.position > from.position ? current_city.higher_item : current_city.lower_item
    end

    legs
  end


  protected

  def compute_amount

    if self.private_shuttle?
      self.amount = self.round_trip? ? self.shuttle.group_round_trip_amount : self.shuttle.group_amount
    else
      #compute base fee for trip
      rate = self.round_trip? ? self.shuttle.round_trip_amount : self.shuttle.amount
      self.amount = self.passengers * rate

      #compute home pickup fees with discount for senior citizens
      home_fee = self.senior_citizen? ? 1000 : 1500
      self.amount += home_fee if self.home_pickup?
      self.amount += home_fee if self.home_dropoff?
    end

  end

  def decrement_shuttle_legs

    if self.private_shuttle?
      shuttle_legs_departing.each { |leg| leg.update_attribute(:available, 0) }
      if(self.round_trip)
        shuttle_legs_returning.each { |leg| leg.update_attribute(:available, 0) }
      end

    else
      shuttle_legs_departing.each { |leg| leg.decrement!(:available, self.passengers) }
      if(self.round_trip)
        shuttle_legs_returning.each { |leg| leg.decrement!(:available, self.passengers) }
      end
    end
  end

  def charge_credit_card
    unless self.added_by_admin
      begin
        Stripe.api_key = ENV['STRIPE_SECRET_KEY']
        Stripe::Charge.create(
          :amount => self.amount,
          :currency => "usd",
          :card => self.token
        )
      rescue Stripe::CardError => e
        errors.add(:credit_card, e.message)
      #rescue => e

      end
    end

  end

  def address_fields_status
    if self.home_pickup
      errors.add(:home_address, "can't be blank") if self.home_address.nil? || self.home_address.blank?
      errors.add(:zipcode, "can't be blank")  if self.zipcode.nil? || self.zipcode.blank?

      if self.round_trip
        errors.add(:round_trip_source_address, "can't be blank") if self.round_trip_source_address.nil? || self.round_trip_source_address.blank?
        errors.add(:round_trip_source_zipcode, "can't be blank")  if self.round_trip_source_zipcode.nil? || self.round_trip_source_zipcode.blank?
      end
    end

    if self.home_dropoff
      errors.add(:dest_address, "can't be blank") if self.dest_address.nil? || self.dest_address.blank?
      errors.add(:dest_zipcode, "can't be blank")  if self.dest_zipcode.nil? || self.dest_zipcode.blank?

      if self.round_trip
        errors.add(:round_trip_dest_address, "should be there") if self.round_trip_dest_address.nil? || self.round_trip_dest_address.blank?
        errors.add(:round_trip_dest_zipcode, "can't be blank")  if self.round_trip_dest_zipcode.nil? || self.round_trip_dest_zipcode.blank?
      end
    end
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_filter :load_shuttle

  layout 'admin'

  def new
    @booking = Booking.new
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.shuttle = @shuttle
    @booking.token = params[:stripeToken] #this is not persisted, just used in a callback

    if @booking.save
      BookingMailer.notify_customer_on_new_booking(@booking).deliver
      BookingMailer.notify_on_new_booking(@booking).deliver
      flash[:success] = "Your shuttle has been booked! You will receive an email confirmation soon."
      render :js => "window.location = '#{url_for(@shuttle)}'"

    else
      render action: 'create_failed'
    end
  end

  def show
    render :layout => 'application'
  end

  def index
    @date = params[:date] ? Date.parse(params[:date]) : Date.today.beginning_of_week
  end


  # Returns dates available for given booking params (which will include number of passengers, from city, to city, and if round_trip)
  def dates
    @booking = Booking.new(booking_params)
    @from = @shuttle.shuttle_cities.find(params[:booking][:from_id])
    @to = @shuttle.shuttle_cities.find(params[:booking][:to_id])

    @depart_dates = []
    @return_dates = []

    if @from != @to

      passengers = @booking.private_shuttle? ? 11 : @booking.passengers

      @depart_dates = @shuttle.dates_for_journey(@from, @to, passengers)
      if @booking.round_trip
        date_range = @booking.depart_date ? (@booking.depart_date + 1)..(@booking.depart_date + 12.months) : Date.today..12.months.from_now
        @return_dates = @shuttle.dates_for_journey(@to, @from, passengers)
      end
    end
  end

  private

  def load_shuttle
    @shuttle = Shuttle.find_by_id(params[:shuttle_id])
  end

  def booking_params
    params.require(:booking).permit( :passengers, :home_pickup, :home_dropoff, :email_address, 
      :home_address, :pickup_city, :zipcode, :telephone_number, :amount, :first_last_name, 
      :phone_number, :round_trip, :from_id, :to_id, :depart_date, :return_date, :added_by_admin, 
      :private_shuttle, :senior_citizen, :dest_address, :dest_city, :dest_zipcode,
      :round_trip_source_address, :round_trip_source_city, :round_trip_source_zipcode, :round_trip_dest_address,
      :round_trip_dest_city, :round_trip_dest_zipcode
      )
  end
end

app/views/bookings/_form.html.haml
:css
  .left_label label{
    text-align: left;
    width: 100%;
  }
  #source_headline, #dest_headline{
    text-align: left;
  }
:javascript
  $(document).ready(function(){
    content_text = "Going to " + $("#booking_to_id  option:selected").text() ;
    $(".source_headline").text(content_text);
    content_text = "Returning from " + $("#booking_to_id  option:selected").text() ;
    $(".dest_headline").text(content_text);

    if( $("#booking_home_dropoff").is(':checked') == true ){
      $("#dest_address").show();
      $("#round_trip_dest_address").show();
    }else{
      $("#dest_address").hide();
      $("#round_trip_dest_address").show();
    }
    if( $("#booking_home_pickup").is(':checked') == true ){
      $("#source_address").show();
      $("#round_trip_source_address").show();
    }else{
      $("#source_address").hide();
      $("#round_trip_source_address").show();
    }

    if( $("#booking_round_trip_true").is(':checked') == true ){
      $("#round_trip_address").show()
    }else{
      $("#round_trip_address").hide()
    }

    $(".alter_address").on("change", function(){
      if( $("#booking_home_dropoff").is(':checked') == true ){
        $("#dest_address").show();
        $("#round_trip_dest_address").show();
      }else{
        $("#dest_address").hide();
        $("#round_trip_dest_address").hide();
      }
      if( $("#booking_home_pickup").is(':checked') == true ){
        $("#source_address").show();
        $("#round_trip_source_address").show();
      }else{
        $("#source_address").hide();
        $("#round_trip_source_address").hide();
      }
      if( $("#booking_round_trip_true").is(':checked') == true ){
        $("#round_trip_address").show()
      }else{
        $("#round_trip_address").hide()
      }
    })

    $('#booking_from_id').on("change", function(){
      $("#booking_pickup_city").val( $("#booking_from_id  option:selected").text() );
      $("#booking_round_trip_dest_city").val( $("#booking_from_id  option:selected").text() );

      content_text = "Going to " + $("#booking_to_id  option:selected").text() ;
      $(".source_headline").text(content_text);
    })

    $('#booking_to_id').on("change", function(){
      $("#booking_pickup_city").val( $("#booking_from_id  option:selected").text() );
      $("#booking_round_trip_dest_city").val( $("#booking_from_id  option:selected").text() );

      content_text = "Going to " + $("#booking_to_id  option:selected").text() ;
      $(".source_headline").text(content_text);

      $("#booking_dest_city").val( $("#booking_to_id  option:selected").text() );
      $("#booking_round_trip_source_city").val( $("#booking_to_id  option:selected").text() );

      content_text = "Returning from " + $("#booking_to_id  option:selected").text() ;
      $(".dest_headline").text(content_text);
    })

  })

= form.select :passengers, options_for_select([*1..11])
.radio-inline
  = form.radio_button :round_trip, false, label: "One Way ($39)", class: 'alter_address'
.radio-inline
  = form.radio_button :round_trip, true, label: "Round Trip ($69)", class: 'alter_address'

= form.check_box :private_shuttle, label: 'Private shuttle (One way - $350, Round trip - $600)'

= form.select :from_id, options_from_collection_for_select(@shuttle.shuttle_cities, :id, :name), class: 'source_loc'
= form.select :to_id, options_from_collection_for_select(@shuttle.shuttle_cities, :id, :name), :include_blank => true, class: 'dest_loc'
= form.hidden_field "depart_date", :id => 'depart_date_hidden_datepicker'
.depart_description
#depart_date_datepicker
= form.hidden_field "return_date", :id => 'return_date_hidden_datepicker'
.return_description
#return_date_datepicker
= form.text_field :first_last_name, label: 'Full name'
= form.text_field :email_address, label: 'Email address (required)'
= form.check_box :home_pickup, label: 'Home pickup: $15.00 ($10.00 for senior citizens)', class: 'alter_address'
= form.check_box :home_dropoff, label: 'Home dropoff:  $15.00 ($10.00 for senior citizens)', class: 'alter_address'
= form.check_box :senior_citizen
.row
  #source_address.col-md-6.left_label
    %h5.source_headline
    = form.text_field :home_address, label: 'Address to be picked up'
    = form.select :pickup_city, ShuttleCity.all.collect(&:name)
    = form.text_field :zipcode
  #dest_address.col-md-6.left_label
    %h5.source_headline
    = form.text_field :dest_address, label: 'Address to be droped off'
    = form.select :dest_city, ShuttleCity.all.collect(&:name), label: 'City'
    = form.text_field :dest_zipcode, label: 'Zipcode'
#round_trip_address.row
  #round_trip_source_address.col-md-6.left_label
    %h5.dest_headline{style: 'text-align:left; margin-left: 20px;'}
    = form.text_field :round_trip_source_address, label: 'Address to be picked up'
    = form.select :round_trip_source_city, ShuttleCity.all.collect(&:name), label: "City"
    = form.text_field :round_trip_source_zipcode, label: 'Zipcode'
  #round_trip_dest_address.col-md-6.left_label
    %h5.dest_headline{style: 'text-align:left; margin-left: 20px;'}
    = form.text_field :round_trip_dest_address, label: 'Address to be dropped off'
    = form.select :round_trip_dest_city, ShuttleCity.all.collect(&:name), label: 'City'
    = form.text_field :round_trip_dest_zipcode, label: 'Zipcode'
= form.text_field :telephone_number, label: 'Telephone number (required)'

app/views/bookings/create_failed.js.erb
jQuery('#payment-form #error_explanation').remove()
jQuery('#payment-form').prepend('<%= escape_javascript(render("shared/error_messages", :object => @booking, :formats => [:html])) %>');

app/views/bookings/index.html.haml
= link_to 'Back to shuttles', shuttles_path, class: 'btn btn-success'
= link_to 'Add Booking', new_shuttle_booking_path, class: 'btn btn-info'
%h2 Bookings for #{@shuttle.name}


%ul.admin_container
  -0.upto 6 do |day|
    -date = @date + day
    %li
      =date.to_formatted_s :human
      - @shuttle.bookings.where(:depart_date => date).each do |booking|
        %ul.admin_row
          %li
            %strong Name:
            #{booking.first_last_name}
          %li
            %strong Passengers:
            #{booking.passengers}
          %li
            %strong Private shuttle?
            #{booking.private_shuttle ? 'Yes' : 'No'}
          %li
            %strong Phone #:
            #{booking.telephone_number.presence || 'N/A'}
          %li
            %strong From:
            #{booking.from.name}
          %li
            %strong To:
            #{booking.to.name}
          %li
            %strong Home pickup?
            #{booking.home_pickup ? 'Yes' : 'No'}
          %li
            %strong Home dropoff?
            #{booking.home_dropoff ? 'Yes' : 'No'}
          %li
            .block
              %strong Pickup Address:
            #{booking.home_address.presence || 'N/A'}
          %li
            .block
              %strong Zipcode
            #{booking.zipcode || 'N/A'}
          %li
            .block
              %strong Destination Address:
            #{booking.dest_address.presence || 'N/A'}
          %li
            .block
              %strong Destination Zipcode
            #{booking.dest_zipcode || 'N/A'}
      - @shuttle.bookings.where(:return_date => date).each do |booking|
        %ul.admin_row
          %li
            %strong Name:
            #{booking.first_last_name}
          %li
            %strong Passengers:
            #{booking.passengers}
          %li
            %strong Private shuttle?
            #{booking.private_shuttle ? 'Yes' : 'No'}
          %li
            %strong From:
            #{booking.to.name}
          %li
            %strong To:
            #{booking.from.name}
          %li
            %strong Home pickup?
            #{booking.home_pickup ? 'Yes' : 'No'}
          %li
            %strong Home dropoff?
            #{booking.home_dropoff ? 'Yes' : 'No'}
          %li
            %strong Phone #:
            #{booking.telephone_number.presence || 'N/A'}
          %li
            .block
              %strong Roundtrip Pick up Address:
            #{booking.round_trip_source_address.presence || 'N/A'}
          %li
            .block
              %strong Roundtrip Pick up Zipcode
            #{booking.round_trip_source_zipcode || 'N/A'}
          %li
            .block
              %strong Roundtrip Drop off Address:
            #{booking.round_trip_dest_address.presence || 'N/A'}
          %li
            .block
              %strong Roundtrip Drop off Zipcode
            #{booking.round_trip_dest_zipcode || 'N/A'}

=link_to "Previous week", date_shuttle_bookings_path(:date => @date - 7)
=link_to "Next week", date_shuttle_bookings_path(:date => @date + 7)

app/views/bookings/new.html.haml
= link_to 'Back to shuttles', shuttles_path, class: 'btn btn-info'

#booking_modal_button{"data-shuttle-id" => @shuttle.id }

= bootstrap_form_for([@shuttle, @booking], html: { id: 'payment-form'}, remote: true) do |f|
  =f.hidden_field :added_by_admin, :value => true
  =render :partial => 'form', :locals => {:form => f}
  .form-group.center
    = f.submit 'Save', class: 'button btn btn-primary'