config/routes.rb
Rails.application.routes.draw do
    root to: 'agm#index'

    get '/agm', to:'agm#index'
    get '/agm/admin', to: 'agm#show'

    resources :tours do
      resources :reservations
    end

    resources :shuttles do
      resources :bookings do
        collection do
          get '/date/:date', :action => :index, :as => :date
          post 'dates'
        end
      end
    end
  get  '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get  'logout', to: 'sessions#destroy'

match '*path', to: redirect{|params| "/#{I18n.default_locale}/#{params[:path]}"}, via: :all
match '', to: redirect("/#{I18n.default_locale}"), via: :all


end

app/models/tour.rb
class Tour < ActiveRecord::Base
  include FlagShihTzu #bitfield flags

  has_many :reservations
  has_many :tour_dates

  after_save :create_missing_tour_dates

  validates :amount, :presence => true

  has_flags 1 => :sunday,
            2 => :monday,
            3 => :tuesday,
            4 => :wednesday,
            5 => :thursday,
            6 => :friday,
            7 => :saturday,
            :column => "day_bits"



  def days
    #returns string like "Monday, Tuesday and Thursday"
    self.selected_day_bits.map(&:capitalize).to_sentence
  end


  private

  def create_missing_tour_dates
    return unless self.tour_date_rebuilt
    self.update_column(:tour_date_rebuilt, false)

    puts "Updating tour date....................."
    puts "Updating tour date....................."
    puts "Updating tour date....................."
    #need to know maximum days into the future that can be booked
    future_days = 365

    date = Date.today
    names = flag_mapping["day_bits"]

    future_days.times do
      if self.day_bits & (2 ** (date.wday)) > 0   # find the bit for each weekday and check if it is flagged
        self.tour_dates.where(:date => date).first_or_create
      else
        present_tour = self.tour_dates.find_by_date(date)
        present_tour.destroy if present_tour && present_tour.available == 11
      end

      date = date + 1
    end

  end
end

app/controllers/tours_controller.rb
class ToursController < ApplicationController
  before_action :require_admin, only: [:index, :new, :edit]

  layout 'admin'

  def index
    @tours = Tour.all
  end

  def new
    @tour = Tour.new
  end

  def create
    @tour = Tour.new(tours_params)
    if @tour.save
      flash[:success] = "Tour #{@tour.name} has been successfully added."
      redirect_to tours_path
    else
      flash[:error] = "The tour #{@tour.name} was not successfully saved. Please try again."
      render 'new'
    end
  end

  def show
    @shuttles = Shuttle.all
    @tours = Tour.all
    @tour = Tour.find_by(id: params[:id])
    @reservation = Reservation.new
    @tour_dates = @tour.tour_dates.where(:date => Date.today .. 12.months.from_now).where("available > 0").order('date asc')

    @tour.save if @tour.tour_date_rebuilt #hack to rebuild dates until a rake task is employeed

    render :layout => 'application'
  end

  def edit
    @tour = Tour.find_by(id: params[:id])
  end

  def update
    @tour = Tour.find_by(id: params[:id])
    @tour.update_column(:tour_date_rebuilt, true)

    if @tour.update_attributes(tours_params)
      flash[:success] = "#{@tour.name} has been successfully updated."
      redirect_to tours_path
    else
      flash[:error] = "#{@tour.name} has not been updated. Please try again."
      render 'edit'
    end
  end

  def destroy
    @tour = Tour.find(params[:id])
    @tour.destroy

    flash[:notice] = "#{@tour.name} has been deleted."
    redirect_to tours_path
  end

  private

  def tours_params
    params.require(:tour).permit(:name, :amount, :time, :location, :duration, :description, :highlights, :start_date,  :sunday, :monday, :tuesday, :wednesday, :thursday, :friday, :saturday)
  end
end

app/views/tours/_form.html.haml
:javascript
  $(function() {
    $( "#tour_start_date" ).datepicker();
  });


= form.text_field :name
= form.text_field 'start_date'
%label Days tour is available on:
- Tour.flag_mapping["day_bits"].each do |day, bit|
  = form.check_box day
= form.text_field :amount, label: 'Amount (in cents per Stripe)'
= form.text_field :time, label: 'Time: (0:00pm)'
= form.text_field :location
= form.text_field :duration, label: 'Duration (In hours)'
= form.text_area :description, rows: 10
= form.text_field :highlights, label: 'Highlights (Seperate with comma)'

app/views/tours/edit.html.haml
= link_to 'Back to tours', tours_path, class: 'btn btn-info'
:javascript
  $(function() {
    $( "#tour_start_date" ).datepicker();
  });
- days = %w(Sun Mon Tue Wed Thu Fri Sat)
.container
  .row
    .col-md-3
      %h2 Edit Tour
      = bootstrap_form_for(@tour) do |f|
        = render :partial => 'form', :locals => {:form => f }
        = f.submit 'Update this tour', class: 'btn btn-success'

app/views/tours/index.html.haml
= link_to 'Add new tour', new_tour_path, class: 'btn btn-success'
= link_to 'Shuttles menu', shuttles_path, class: 'btn btn-info'
= link_to 'Logout', logout_path, class: 'btn btn-danger'
%h2 List of all tours available
- @tours.each do |tour|
  %ul
    %li
      = link_to tour.name, tour
    %li
      %strong Price: $
      = ' %.2f' % (tour.amount.to_i/100.0)
      %strong
        %li Days tour is available on:
    %li= tour.days
    = link_to 'Reservations', tour_reservations_path(tour)
    = link_to 'Edit', edit_tour_path(tour)
    = link_to "Delete tour",
      tour_path(tour),
      method: :delete,
      data: { confirm: "Are you sure you want to delete this tour" }

app/views/tours/new.html.haml
= link_to 'Back to tours', tours_path, class: 'btn btn-info'
:javascript
  $(function() {
    $( "#tour_start_date" ).datepicker();
  });
.container
  .row
    .col-md-3
      %h2 Add New Tour
      = bootstrap_form_for(@tour) do |f|
        = render :partial => 'form', :locals => {:form => f }
        = f.submit 'Add this tour', class: 'btn btn-success'

app/views/tours/show.haml
= stylesheet_link_tag 'localtours'
= javascript_include_tag "https://js.stripe.com/v2/"
= javascript_include_tag 'payment'
:javascript
  Stripe.setPublishableKey("#{ENV['STRIPE_PUBLISHABLE_KEY']}");
.container.main-heading
  .row
    %h2.padding-bottom
      = @tour.name
  .row
    .col-md-4.tour-images
      - if @tour.name == 'Hoover Dam Tour'
        = image_tag('hoover-dam.jpg', alt: 'Hoover Dam Tour')
      - if @tour.name == 'Las Vegas City Tour'
        = image_tag('city-tour.jpg', alt: 'Las Vegas City Tour')
      - if @tour.name == 'Red Rock Canyon Tour'
        = image_tag('red-rock.jpg')
      - if @tour.name == 'Valley of Fire Tour'
        = image_tag('valley-of-fire.jpg', alt: 'Valley of Fire Tour')
      - if @tour.name == 'Grand Canyon Tour'
        = image_tag('grand-canyon2.jpg', alt: 'Grand Canyon Tour')
      - if @tour.name == 'Death Valley Tour'
        = image_tag('death-valley.jpg', alt: 'Death Valley Tour')
    .col-md-4.tour-images
      - if @tour.name == 'Hoover Dam Tour'
        = image_tag('hoover-dam2.jpg', alt: 'Hoover Dam Tour')
      - if @tour.name == 'Las Vegas City Tour'
        = image_tag('city-tour2.jpg', alt: 'Las Vegas City Tour')
      - if @tour.name == 'Red Rock Canyon Tour'
        = image_tag('red-rock2.jpg', alt: 'Red Rock Canyon Tour')
      - if @tour.name == 'Valley of Fire Tour'
        = image_tag('valley-of-fire2.jpg', alt: 'Valley of Fire Tour')
      - if @tour.name == 'Grand Canyon Tour'
        = image_tag('grand-canyon.jpg', alt: 'Grand Canyon Tour')
      - if @tour.name == 'Death Valley Tour'
        = image_tag('death-valley2.jpg', alt: 'Death Valley Tour')
    .col-md-4.tour-images
      - if @tour.name == 'Hoover Dam Tour'
        = image_tag('hoover-dam3.jpg', alt: 'Hooer Dam Tour')
      - if @tour.name == 'Las Vegas City Tour'
        = image_tag('city-tour3.jpg', alt: 'Las Vegas City Tour')
      - if @tour.name == 'Red Rock Canyon Tour'
        = image_tag('red-rock3.jpg', alt: 'Red Rock Canyon Tour')
      - if @tour.name == 'Valley of Fire Tour'
        = image_tag('valley-of-fire3.jpg', alt: 'Valley of Fire Tour')
      - if @tour.name == 'Grand Canyon Tour'
        = image_tag('grand-canyon3.jpg', alt: 'Grand Canyon Tour')
      - if @tour.name == 'Death Valley Tour'
        = image_tag('death-valley3.jpg', alt: 'Death Valley Tour')
  .row.margin-top
    .col-md-8.reservations-left
      %h3.padding-bottom
        = @tour.name
      .tour-info
        %p.padding-bottom
          = @tour.description
        %h4 Information:
        %ul.padding-bottom
          %li
            Duration: #{@tour.duration}
        %h4 Departure point and time:
        %ul.padding-bottom
          %li
            #{@tour.location} at #{@tour.time}
        %h4 Amenities
        %ul.list-inline.padding-bottom
          %li
            = image_tag('wifi_icon.png', alt: 'Wifi', width: 52, height: 42)
            %span.small-text
              Wifi
              %span
          %li
            = image_tag('water_icon.png', alt: 'Wifi', width: 40, height: 40)
            %span.small-text Water
          %li
            = image_tag('snack_icon.png', alt: 'Wifi', width: 34, height: 36)
            %span.small-text Snacks
        %h4 Tour highlights
        %ul.padding-bottom
          - highlights = @tour.highlights
          - highlights_a = highlights.split(/,/)
          - highlights = highlights_a.join(', ')
          - highlights_a.each do |hl|
            %li= hl
        %h4 Additional info
        %ul
          %li All tours are available with 5-11 passengers
          %li Pricing is the same for adults and children
          %li If traveling with a child, please bring your own car seat
        %h4 Other options
        %p Please call us at 702 327 9922 if you would like to customize your tour, including the tour time.
    .col-md-4.reservations-right
      %h3.padding-bottom Book this tour
      .pricing-notice
        %p Pricing is for both adults and children
      %h3.blue-heading
        $
        #{p '%.2f' % (@tour.amount.to_i/100.0)}
      = bootstrap_form_for([@tour, @reservation], html: { id: 'payment-form'}, remote: true) do |f|
        =render :partial => 'reservations/form', :locals => {:form => f}
        %span.payment-errors
        .form-group
          = label_tag :card_number, 'Credit card number:'
          = text_field_tag :card_number, nil, name: nil, class: 'form-control', data: {stripe: 'number'}
        .form-group
          = label_tag :security_code, 'Security code:'
          = text_field_tag :security_code, nil, name: nil, class: 'form-control', data: {stripe: 'cvc'}
        .form-group
          = label_tag :exp_date, 'Expiration:'
        .form-group
          = select_month(Date.today, {add_month_numbers: true},  class: 'form-control', data: {stripe: 'exp-month'})
          = select_year(Date.today.year, {start_year: Date.today.year, end_year: Date.today.year + 4}, class: 'form-control', data: {stripe: 'exp-year'})
        .form-group
          %h4.text-center Terms & Conditions
          %p.text-center No refunds. All sales are final. You’re only guaranteed a seat with a valid reservation.
        .form-group.center
          = f.submit 'BOOK TOUR', class: 'button btn btn-primary'