config/routes.rb
Rails.application.routes.draw do
    root to: 'agm#index'

    get '/agm', to:'agm#index'
    get '/agm/admin', to: 'agm#show'

    resources :tours do
      resources :reservations
    end

    resources :shuttles do
      resources :bookings do
        collection do
          get '/date/:date', :action => :index, :as => :date
          post 'dates'
        end
      end
    end
  get  '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get  'logout', to: 'sessions#destroy'

match '*path', to: redirect{|params| "/#{I18n.default_locale}/#{params[:path]}"}, via: :all
match '', to: redirect("/#{I18n.default_locale}"), via: :all


end

app/models/shuttle.rb
class Shuttle < ActiveRecord::Base
  include FlagShihTzu #bitfield flags

  has_many :bookings

  has_many :shuttle_cities, -> { order('position asc') }
  has_many :shuttle_legs

  accepts_nested_attributes_for :shuttle_cities

  validates :amount, :presence => true
  validates :round_trip_amount, :presence => true
  validates :group_amount, :presence => true
  validates :group_round_trip_amount, :presence => true

  after_save :create_missing_shuttle_legs

  has_flags 1 => :sunday,
            2 => :monday,
            3 => :tuesday,
            4 => :wednesday,
            5 => :thursday,
            6 => :friday,
            7 => :saturday,
            :column => "day_bits"


  def dates_for_journey(from, to, passengers, date_range = Date.today..12.months.from_now)

    dates = self.shuttle_legs.where(:from_id => from, :date => date_range).where(["available >= ?",passengers]).map &:date
    current_city = to.position > from.position ? from.lower_item : from.higher_item

    #intersect the set of dates that match for each leg of the journey if there are multiple legs
    while( current_city && current_city != to )
      matches = self.shuttle_legs.where(:from_id => current_city, :date => date_range).where(["available >= ?",passengers]).map &:date
      dates = dates & matches
      current_city = to.position > from.position ? current_city.lower_item : current_city.higher_item

    end

    return [] if current_city != to

    dates
  end


  def days
    #returns string like "Monday, Tuesday and Thursday"
    self.selected_day_bits.map(&:capitalize).to_sentence
  end


  private

  def create_missing_shuttle_legs
    return unless self.shuttle_lag_rebuilt
    self.update_column(:shuttle_lag_rebuilt, false)

    future_days = 365

    date = Date.today
    names = flag_mapping["day_bits"]

    future_days.times do
      if self.day_bits & (2 ** (date.wday)) > 0
        self.shuttle_cities.each_cons(2) do |from, to|
          self.shuttle_legs.where(:date => date, :from => from, :to => to).first_or_create
        end

        self.shuttle_cities.reverse.each_cons(2) do |from, to|
          self.shuttle_legs.where(:date => date, :from => from, :to => to).first_or_create
        end
      else
        self.shuttle_cities.each_cons(2) do |from, to|
          present_shuttles = self.shuttle_legs.where(:date => date, :from => from, :to => to)
          present_shuttles.each do |shuttle|
            shuttle.destroy if shuttle && shuttle.available == 11
          end
        end

        self.shuttle_cities.reverse.each_cons(2) do |from, to|
          present_shuttles = self.shuttle_legs.where(:date => date, :from => from, :to => to)
          present_shuttles.each do |shuttle|
            shuttle.destroy if shuttle && shuttle.available == 11
          end
        end
      end

      date = date + 1
    end

  end
end

app/controllers/shuttles_controller.rb
class ShuttlesController < ApplicationController
  before_action :require_admin, only: [:index, :new, :edit]
  before_action :load_shuttle, only: [:show, :edit, :update, :destroy]

  layout 'admin'

  def index
    @shuttles = Shuttle.all
  end

  def new
    @shuttle = Shuttle.new
    # @shuttle.shuttle_cities.build
  end

  def create
    @shuttle = Shuttle.new(shuttles_params)
    if @shuttle.save
      flash[:success] = "shuttle #{@shuttle.name} has been successfully added."
      redirect_to shuttles_path
    else
      flash[:error] = "The shuttle #{@shuttle.name} was not successfully saved. Please try again."
      render 'new'
    end
  end

  def show
    @shuttles = Shuttle.all
    @tours = Tour.all
    @booking = Booking.new
    @from_cities = @shuttle.shuttle_cities
    @to_cities = @shuttle.shuttle_cities

    @shuttle.save  if @shuttle.shuttle_lag_rebuilt #hack to rebuild dates until a rake task is employeed

    render :layout => 'application'
  end

  def edit
  end

  def update
    @shuttle.update_column(:shuttle_lag_rebuilt, true)
    if @shuttle.update_attributes(shuttles_params)
      flash[:success] = "#{@shuttle.name} has been successfully updated."
      redirect_to shuttles_path
    else
      flash[:error] = "#{@shuttle.name} has not been updated. Please try again."
      render 'edit'
    end
  end

  def destroy
    @shuttle.destroy

    flash[:notice] = "#{@shuttle.name} has been deleted."
    redirect_to shuttles_path
  end


  private

  def load_shuttle
    @shuttle = Shuttle.find_by_id(params[:id])

    #Temporary fix for home page
    redirect_to Shuttle.first unless @shuttle

  end

  def shuttles_params
    params.require(:shuttle).permit(:name, :amount, :start_date, :sunday, :monday, :tuesday, :wednesday, :thursday, :friday, :saturday, {:shuttle_cities_attributes => [:id, :name]}, :round_trip_amount, :group_amount, :group_round_trip_amount )
  end
end

app/views/shuttles/_form.html.haml
= form.text_field :name, label: 'Name:'
= form.text_field 'start_date', label: 'Start date of shuttle:'
%label Days shuttle is available on
- Shuttle.flag_mapping["day_bits"].each do |day, bit|
  = form.check_box day

= form.text_field :amount, label: 'Amount (in cents per Stripe)'
= form.text_field :round_trip_amount
= form.text_field :group_amount
= form.text_field :group_round_trip_amount

Route
#shuttle_cities.items
  =form.nested_fields_for :shuttle_cities do |fields|
    %fieldset.item
      =link_to 'x', '', :class => 'remove' if fields.object.new_record?
      =fields.text_field :name, :label => "City"
      =fields.hidden_field :id

%a.add.btn.btn-info.btn-xs{:href => '#'} Add City

.spacer

:coffeescript
  jQuery ->
   jQuery('form').nestedFields();

app/views/shuttles/edit.html.haml
= link_to 'Logout', logout_path, class: 'btn btn-danger'
:javascript
  $(function() {
    $( "#shuttle_start_date" ).datepicker();
  });
- days = %w(Sun Mon Tue Wed Thu Fri Sat)
.container
  .row
    .col-md-3
      %h2 Edit shuttle
      = bootstrap_form_for(@shuttle) do |f|
        = render :partial => 'form', :locals => {:form => f}
        = f.submit 'Update Shuttle', class: 'btn btn-success'

app/views/shuttles/index.html.haml
= link_to 'Add new shuttle', new_shuttle_path, class: 'btn btn-success'
= link_to 'Tours menu', tours_path, class: 'btn btn-info'
= link_to 'Logout', logout_path, class: 'btn btn-danger'
%h2 List of all shuttles available
- @shuttles.each do |shuttle|
  %ul
    %li
      = link_to shuttle.name, shuttle
    %strong
      %li Pricing:
    %li
      One way: $#{' %.2f' % (shuttle.amount.to_i/100.0)}
    %li
      Round trip: $#{' %.2f' % (shuttle.round_trip_amount.to_i/100.00)}
    %li
      Private (one way): $#{' %.2f' % (shuttle.group_amount.to_i/100.00)}
    %li
      Private (round trip): $#{' %.2f' % (shuttle.group_round_trip_amount.to_i/100.00)}
    %strong
      %li Days shuttle available on:
    %li= shuttle.days
    = link_to 'Edit', edit_shuttle_path(shuttle)
    = link_to 'Bookings', shuttle_bookings_path(shuttle)
    = link_to "Delete shuttle",
      shuttle_path(shuttle),
      method: :delete,
      data: { confirm: "Are you sure you want to delete this shuttle" }

app/views/shuttles/new.html.haml
= link_to 'Back to shuttles', shuttles_path, class: 'btn btn-info'
:javascript
  $(function() {
    $( "#shuttle_start_date" ).datepicker();
  });
- days = %w(Sun Mon Tue Wed Thu Fri Sat)
.container
  .row
    .col-md-3
      %h2 Add new shuttle
      = bootstrap_form_for(@shuttle) do |f|
        = render :partial => 'form', :locals => {:form => f}
        = f.submit 'Add this shuttle', class: 'btn btn-success'

app/views/shuttles/show.html.haml
= stylesheet_link_tag 'express'
= javascript_include_tag "https://js.stripe.com/v2/"
= javascript_include_tag 'payment'
:javascript
  Stripe.setPublishableKey("#{ENV['STRIPE_PUBLISHABLE_KEY']}");
.about-us
  .container
    #agm-slideshow.col-md-5.carousel.slide{"data-pause" => "hover", "data-ride" => "carousel"}
      %ol.carousel-indicators
        %li.active{"data-slide-to" => "0", "data-target" => "#agm-slideshow"}
        %li{"data-slide-to" => "1", "data-target" => "#agm-slideshow"}
        %li{"data-slide-to" => "2", "data-target" => "#agm-slideshow"}
        %li{"data-slide-to" => "3", "data-target" => "#agm-slideshow"}
        %li{"data-slide-to" => "4", "data-target" => "#agm-slideshow"}
        %li{"data-slide-to" => "5", "data-target" => "#agm-slideshow"}
        %li{"data-slide-to" => "6", "data-target" => "#agm-slideshow"}
        %li{"data-slide-to" => "7", "data-target" => "#agm-slideshow"}
        %li{"data-slide-to" => "8", "data-target" => "#agm-slideshow"}
        %li{"data-slide-to" => "9", "data-target" => "#agm-slideshow"}
      .carousel-inner
        .item.active
          = image_tag('van-3.JPG', alt: 'Las Vegas, Hollywood, Glendale Express VIP Shuttle')
        .item
          = image_tag('van-1.JPG', alt: 'Las Vegas, Hollywood, Glendale Express VIP Shuttle')
        .item
          = image_tag('van-2.JPG', alt: 'Las Vegas, Hollywood, Glendale Express VIP Shuttle')
        .item
          = image_tag('van-4.JPG', alt: 'Las Vegas, Hollywood, Glendale Express VIP Shuttle')
        .item
          = image_tag('van-5.JPG', alt: 'Las Vegas, Hollywood, Glendale Express VIP Shuttle')
        .item
          = image_tag('van-6.JPG', alt: 'Las Vegas, Hollywood, Glendale Express VIP Shuttle')
        .item
          = image_tag('van-7.JPG', alt: 'Las Vegas, Hollywood, Glendale Express VIP Shuttle')
        .item
          = image_tag('van-8.JPG', alt: 'Las Vegas, Hollywood, Glendale Express VIP Shuttle')
        .item
          = image_tag('van-9.JPG', alt: 'Las Vegas, Hollywood, Glendale Express VIP Shuttle')
        .item
          = image_tag('van-10.JPG', alt: 'Las Vegas, Hollywood, Glendale Express VIP Shuttle')
      %a.left.carousel-control{"data-slide" => "prev", href: "#agm-slideshow"}
        %span
      %a.right.carousel-control{"data-slide" => "next", href: "#agm-slideshow"}
        %span
    .col-md-7.about-us-text
      %h2= t 'shuttles.title'
      %p= t 'shuttles.description1'
      %p.strong-text= t 'shuttles.description2'
      %ul.list-inline
        %li= t 'shuttles.city1'
        %li= t 'shuttles.city2'
        %li= t 'shuttles.city3'
      %small= t 'shuttles.notice'

.tours-information.text-center
.container
  .schedule-listing.col-md-9
    %table
      %thead
        %tr.black-border.grey-bg
          %th.no-padding
            %h5.square-heading= t 'shuttles.weekdays'
          %th
            %h4= t 'shuttles.departure'
          %th
            %h4= t 'shuttles.arrival'
          %th
      %thead
        %tr
          %th.long-arrow-bg
            %h2 Las Vegas
            = image_tag("double_arrow.png", class: 'visible-lg')
          %th
          %th
            %h2 Glendale
          %th.short-arrow-bg
            %h2 Hollywood
            = image_tag("single_arrow.png", class: 'visible-lg')
      %tbody
        %tr
          %td
            %span.visible-xs.visible-md= t 'shuttles.friday'
            %span.visible-xs.visible-md= t 'shuttles.departure'
            %h3 8:00am
            3389 S Jones Blvd
            %br/
            Las Vegas, NV 89146
            %br/
            %span.strong-text (Jones Market)
          %td.padding-top
            %h3 8:30am
            3801 S. LV Blvd.
            %br/
            Las Vegas, NV 89109)
            %br/
            %span.strong-text (Tropicana Hotel)
          %td.padding-top
            %span.visible-xs.visible-md= t 'shuttles.Friday'
            %span.visible-xs.visible-md= t 'shuttles.arrival'
            %h3 1:00pm
            1717 W. Glenoaks Blvd.
            %br/
            Glendale, CA 91201
            %br/
            %span.strong-text (Jons Market)
          %td
            %h3 1:30pm
            1601 N. Vermont Ave.
            %br/
            Los Angeles, CA 90027
            %br/
            %span.strong-text (Jons Market)
      %thead
        %tr
          %th.short-arrow-bg2
            %h2 Hollywood
            = image_tag("single_arrow.png", class: 'visible-lg')
          %th
            %h2 Glendale
          %th
          %th.long-arrow-bg2.img
            %h2 Las Vegas
            = image_tag("double_arrow.png", class: 'visible-lg')
      %tbody
        %tr
          %td
            %span.visible-xs.visible-md= t 'shuttles.friday'
            %span.visible-xs.visible-md= t 'shuttles.departure'
            %h3 7:00PM
            1601 N. Vermont Ave.
            %br/
            Los Angeles, CA 90027
            %br/
            %span.strong-text (Jones Market)
          %td.padding-top
            %h3 7:30pm
            1717 W. Glenoaks Blvd.
            %br/
            Glendale, CA 91201
            %br/
            %span.strong-text (Jones Market)
          %td.padding-top
            %span.visible-xs.visible-md
              %strong Friday
            %span.visible-xs.visible-md
              %strong Arrival
            %h3 12:00am
            3801 S. LV Blvd.
            %br/
            Las Vegas, NV 89109
            %br/
            %span.strong-text (Tropicana Hotel)
          %td
            %h3 12:15am
            3389 S Jones Blvd.
            %br/
            Las Vegas, NV 89146
            %br/
            %span.strong-text (Jones Market)
    %table
      %thead
        %tr.black-border.grey-bg
          %th.no-padding
            %h5.square-heading= t 'shuttles.sunday'
          %th
            %h4= t 'shuttles.departure'
          %th
            %h4= t 'shuttles.arrival'
          %th
      %thead
        %tr
          %th.long-arrow-bg
            %h2 Las Vegas
            = image_tag("double_arrow.png", class: 'visible-lg')
          %th
          %th
            %h2 Glendale
          %th.short-arrow-bg.img
            %h2 Hollywood
            = image_tag("single_arrow.png", class: 'visible-lg')
      %tbody
        %tr
          %td
            %span.visible-xs.visible-md= t 'shuttles.sunday'
            %span.visible-xs.visible-md= t 'shuttles.departure'
            %h3 9:30am
            3389 S Jones Blvd
            %br/
            Las Vegas, NV 89146
            %br/
            %span.strong-text (Jones Market)
          %td.padding-top
            %h3 10:00am
            3801 S. LV Blvd.
            %br/
            Las Vegas, NV 89109)
            %br/
            %span.strong-text (Tropicana Hotel)
          %td.padding-top
            %span.visible-xs.visible-md= t 'shuttles.sunday'
            %span.visible-xs.visible-md= t 'shuttles.arrival'
            %h3 2:30pm
            1717 W. Glenoaks Blvd.
            %br/
            Glendale, CA 91201
            %br/
            %span.strong-text (Jons Market)
          %td
            %h3 3:00pm
            1601 N. Vermont Ave.
            %br/
            Los Angeles, CA 90027
            %br/
            %span.strong-text (Jons Market)
      %thead
        %tr
          %th.short-arrow-bg2
            %h2 Hollywood
            = image_tag("single_arrow.png", class: 'visible-lg')
          %th
            %h2 Glendale
          %th
          %th.long-arrow-bg2.img
            %h2 Las Vegas
            = image_tag("double_arrow.png", class: 'visible-lg')
      %tbody
        %tr
          %td
            %span.visible-xs.visible-md= t 'shuttles.sunday'
            %span.visible-xs.visible-md= t 'shuttles.departure'
            %h3 7:00pm
            1601 N. Vermont Ave.
            %br/
            Los Angeles, CA 90027
            %br/
            %span.strong-text (Jons Market)
          %td.padding-top
            %h3 7:30pm
            1717 W. Glenoaks Blvd.
            %br/
            Glendale, CA 91201
            %br/
            %span.strong-text (Jones Market)
          %td.padding-top
            %span.visible-xs.visible-md= t 'shuttles.sunday'
            %span.visible-xs.visible-md= t 'shuttles.arrival'
            %h3 12:00am
            3801 S. LV Blvd.
            %br/
            Las Vegas, NV 89109
            %br/
            %span.strong-text (Tropicana Hotel)
          %td
            %h3 12:15am
            3389 S Jones Blvd.
            %br/
            Las Vegas, NV 89146
            %br/
            %span.strong-text (Jones Market)
        %tr
    .shuttle-notice
      %p= t 'shuttles.notice2'
  .tour-details.col-md-3
    .row.margin-bottom
      .pricing.text-center
        %h3= t 'pricing.title'
        %p= t 'pricing.description'
        #pricing-reservations
          %ul
            %li.large-text
              #{t 'pricing.oneway'}          
              %span.pricing-reservations-large-price-one-way $39
            %li.large-text
              #{t 'pricing.roundtrip'}          
              %span.pricing-reservations-large-price $69
          %button#booking_modal_button.btn.btn-primary.btn-lg{"data-shuttle-id" => @shuttle.id, "data-target" => "#booking_modal", "data-toggle" => "modal"}
            #{t 'pricing.bookbutton'}
          #booking_modal.modal.large{"aria-hidden" => "true", "aria-labelledby" => "myModalLabel", role: "dialog", tabindex: "-1"}
            .modal-dialog
              .modal-content
                .modal-header
                  %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", type: "button"} ×
                  %h4#myModalLabel.modal-title= t 'booking.title'
                .modal-body
                  = render 'layouts/messages'
                  %p.small-text Pricing is for both adults and children
                  = bootstrap_form_for([@shuttle, @booking], html: { id: 'payment-form'}, remote: true) do |f|
                    =render :partial => 'bookings/form', :locals => {:form => f}
                    %span.payment-errors
                    .form-group
                      = label_tag :card_number, 'Credit card number:'
                      = text_field_tag :card_number, nil, name: nil, class: 'form-control', data: {stripe: 'number'}
                    .form-group
                      = label_tag :security_code, 'Security code:'
                      = text_field_tag :security_code, nil, name: nil, class: 'form-control', data: {stripe: 'cvc'}
                    .form-group
                      = label_tag :exp_date, 'Expiration:'
                    .form-group
                      = select_month(Date.today, {add_month_numbers: true},  class: 'form-control', data: {stripe: 'exp-month'})
                      = select_year(Date.today.year, {start_year: Date.today.year, end_year: Date.today.year + 4}, class: 'form-control', data: {stripe: 'exp-year'})
                    .modal-footer
                    .form-group.center
                      %h4 Terms & Conditions
                      %p No refunds. All sales are final. You’re only guaranteed a seat with a valid reservation.
                      %button.btn.btn-default{"data-dismiss" => "modal", type: "button"} Close
                      = f.submit 'Book Now', class: 'button btn btn-primary'
          %p.text-center.margin-top
            %strong= t 'pricing.bookingoptions'
          .text-center
            %h3#pricing-reservations-telephone 702 327 9922
          %ul.list-inline.text-center
            %li
              = image_tag("visa_logo.png")
            %li
              = image_tag("mastercard_logo.png")
            %li
              = image_tag("americanexpress_logo.png")
            %li
              = image_tag("discover_logo.png")
    .row.margin-bottom
      .amenities.text-center
        %h3 Amenities
        %p Enjoy the following amenities on our shuttles:
        %ul.list-inline
          %li
            = image_tag('wifi_icon.png', alt: 'Wifi', width: 52, height: 42)
            %span.small-text
              Wifi
              %span
          %li
            = image_tag('water_icon.png', alt: 'Wifi', width: 40, height: 40)
            %span.small-text Water
          %li
            = image_tag('snack_icon.png', alt: 'Wifi', width: 34, height: 36)
            %span.small-text Snacks
    .row
      .keep-in-touch.text-center
        %h3 Keep in touch
        %p Find us on:
        %ul.list-inline
          %li
            = link_to(image_tag("facebook_icon.png", width: 48, height: 42), "https://www.facebook.com/agmtoursinc")
            = link_to(image_tag("twitter_icon.png", width: 48, height: 42), "https://twitter.com/AGMToursInc")