config/routes.rb
Rails.application.routes.draw do
    root to: 'agm#index'

    get '/agm', to:'agm#index'
    get '/agm/admin', to: 'agm#show'

    resources :tours do
      resources :reservations
    end

    resources :shuttles do
      resources :bookings do
        collection do
          get '/date/:date', :action => :index, :as => :date
          post 'dates'
        end
      end
    end
  get  '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get  'logout', to: 'sessions#destroy'

match '*path', to: redirect{|params| "/#{I18n.default_locale}/#{params[:path]}"}, via: :all
match '', to: redirect("/#{I18n.default_locale}"), via: :all


end

app/views/layouts/_messages.html.erb
<% flash.each do |type, message| %>
  <div class="alert <%= bootstrap_class_for(type) %>">
    <button class="close" data-dismiss="alert">×</button>
    <%= message %>
  </div>
<% end %>

app/views/layouts/_messages.html.haml
- flash.each do |type, message|
  %div{class: "alert #{bootstrap_class_for(type)}"}
    %button.close{"data-dismiss" => "alert"} ×
    = message

app/views/layouts/admin.html.haml
!!!
%html
  %head
    %title Welcome to AGM Tours, Inc.
    %meta{content: "width=device-width, initial-scale=1", name: "viewport"}/
    = stylesheet_link_tag    'admin', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'admin', 'data-turbolinks-track' => true
    = csrf_meta_tags
    %link{href: "http://fonts.googleapis.com/css?family=Arimo:400,700", rel: "stylesheet", type: "text/css"}/
    %link{href: "http://fonts.googleapis.com/css?family=Didact+Gothic", rel: "stylesheet", type: "text/css"}/
    %link{href: "http://fonts.googleapis.com/css?family=Just+Another+Hand|Dancing+Script", rel: "stylesheet", type: "text/css"}/
  %body

    .container-fluid
      .row
        .col-md-12
          = render 'layouts/messages'
          = yield

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Welcome to AGM Tours, Inc.</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="We offer Express Shuttle Service and VIP Tours in the United States.">
  <meta name="keywords" content="shuttle, tours, mercedes sprinter, VIP Tour, Las Vegas City Tour, Grand Canyon Tour, Hoover Dam Tour, Death Valley Tour, Red Rock Canyon Tour, Valley of Fire tour, Hollywood Shuttle, Glendale Shuttle, Las Vegas Shuttle ">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href='http://fonts.googleapis.com/css?family=Didact+Gothic' rel='stylesheet' type='text/css'>
</head>
<body>

<div class='jumbotron'>
    <div class='container heading'>
        <div class='col-md-8'>
          <div id='jumbotron-logo'>
            <h1><%= link_to(image_tag('logo.png', alt: 'AGM Logo', class: 'img-responsive'), root_path) %></h1>
          </div>
        </div>
        <div class="col-md-4 heading-right-container">
          <div id="translate">
            <%= link_to(image_tag("flag-icon-usa.png"), locale: 'en') %>
            <%= link_to(image_tag("flag-icon-armenia.png"), locale: 'am')%>
          </div>
        </div>

        <div id="jumbotron-telephone-text">
          <span class="medium-text">Please</span>
          <span class="larger-text">call us</span>
          <span class="medium-text">for</span>
          <span class="larger-text">reservations</span>
        </div>
        <div id='jumbotron-telephone'>
          <h2>702 327 9922</h2>
        </div>

        <div class='col-md-12 col-sm-8'>
            <ul class='nav nav-pills'>
              <li class="<%= 'active' if current_page?('/') %>"><%= link_to 'Home', root_path %></li>
              <% @shuttles.each do |shuttle| %>
                <li class="<%= 'active' if current_page?(shuttle_path(shuttle)) %>"><%= link_to shuttle.name, shuttle %></li>
              <% end %>
              <% @tours.each do |tour| %>
                  <li class="<%= 'active' if current_page?(tour_path(tour)) %>"><%= link_to tour.name, tour %></li>
              <% end %>
            </ul>
        </div>
    </div>
</div>

<div class="container-fluid">
  <div class="row">
    <div class="col-md-12">
      <%= render 'layouts/messages' %>
      <%= yield %>
    </div>
  </div>
  <footer>
    <div class='container'>
      <div class='row'>
        <div class='col-md-8'>
          <div class='copyright'>
            <small>&copy; 2014 AGM Tours, Inc.</small>
            <small>USDOT: 2479956 MC: 858186</small>
            <strong><small>Bookings by phone: 702 327 9922</small></strong>
          </div>
        </div>

        <div class='col-md-4'>
          <div id='social-media'>
            <strong><small>Find us on:</small></strong>
              <%= link_to(image_tag("facebook_icon.png", width: 24, height: 24), "https://www.facebook.com/agmtoursinc") %>
              <%= link_to(image_tag("twitter_icon.png", width: 24, height: 24), "https://twitter.com/AGMToursInc") %>
              <%= link_to 'Admin', login_path, class: 'mini-text' %>
          </div>
        </div>
      </div>
    </div>
  </footer>
</div>
</body>
</html>